fix nm, hardcoded

diff --git a/ft_nm/Makefile b/ft_nm/Makefile
--- a/ft_nm/Makefile
+++ b/ft_nm/Makefile
@@ -3,13 +3,16 @@ NAME = ft_nm
 # Diretórios
 SRC_DIR = src
 OBJDIR = obj
+LIBFT_DIR = ./libft
 INCLUDE_DIR = include
+DEPS = include/ft_nm.h
 
-
+# Libft
+LIBFT = -L $(LIBFT_DIR) -lft
 
 # Headers
-HEADERS = $(wildcard $(INCLUDE_DIR)/*.h)
-INCLUDES = -I$(INCLUDE_DIR) 
+HEADERS = $(wildcard $(INCLUDE_DIR)/*.h) $(wildcard $(LIBFT_DIR)/*.h)
+INCLUDES = -I$(INCLUDE_DIR) -I$(LIBFT_DIR)/include 
 
 # Compilador e flags
 CC = gcc
@@ -28,21 +31,20 @@ $(info Headers: $(HEADERS))
 $(info =====================)
 
 # Regras
-all: mk_objdir  $(NAME)
+all: mk_objdir libft $(NAME)
 
 mk_objdir:
 	@mkdir -p $(OBJDIR)
 	@echo "Created object directory: $(OBJDIR)"
 
-simple:
-	gcc -o simple simple.c
-	gcc -c simple.c -o simple.o
-	gcc -m32 -c simple.c -o simple_32.o 2>/dev/null
+libft:
+	@echo "Building libft..."
+	@make -C $(LIBFT_DIR)
 
-
+# Corrigido: mudou de $(OBJS) para $(OBJ)
 $(NAME): $(OBJ)
 	@echo "Linking $(NAME)..."
-	@$(CC) $(CFLAGS) $(SANITIZE) $(OBJ)  -o $(NAME)
+	@$(CC) $(CFLAGS) $(SANITIZE) $(OBJ) $(LIBFT) -o $(NAME)
 	@echo "\033[1;32m$(NAME) built successfully!\033[0m"
 
 $(OBJDIR)/%.o: $(SRC_DIR)/%.c $(HEADERS)
@@ -51,10 +53,12 @@ $(OBJDIR)/%.o: $(SRC_DIR)/%.c $(HEADERS)
 
 clean:
 	@echo "Cleaning objects..."
+	@make clean -C $(LIBFT_DIR)
 	@rm -rf $(OBJDIR)
 
 fclean: clean
 	@echo "Cleaning everything..."
+	@make fclean -C $(LIBFT_DIR)
 	@rm -f $(NAME)
 	@echo "\033[1;33mAll cleaned!\033[0m"
 
@@ -67,6 +71,8 @@ check:
 	@ls -la $(SRC_DIR) || echo "$(SRC_DIR) not found!"
 	@echo "\nChecking include directory:"
 	@ls -la $(INCLUDE_DIR) || echo "$(INCLUDE_DIR) not found!"
+	@echo "\nChecking libft directory:"
+	@ls -la $(LIBFT_DIR) || echo "$(LIBFT_DIR) not found!"
 	@echo "\nChecking headers:"
 	@for header in $(HEADERS); do \
 		if [ -f $$header ]; then \
@@ -76,4 +82,4 @@ check:
 		fi \
 	done
 
-.PHONY: all clean fclean re mk_objdir  check
+.PHONY: all clean fclean re mk_objdir libft check
